backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  name: github
  repo: sthorng/11ty-test
media_folder: 'src/static/img'
public_folder: '/static/img'

local_backend: true
publish_mode: editorial_workflow
